### PR TITLE
Fix link to Rust RFCs in README

### PR DESCRIPTION
**Pull request by haikoschol**

### CODE REVIEW

**Comment by yurishkuro** [comment]
CLA check is failing

**Comment by haikoschol** [comment]
I signed it and got an email with the document. Anything else I need to do?

**Comment by bogdandrutu** [comment]
@open-telemetry/specs-approvers please review (this is trivial, I will merge it as admin if we don't get enough LGTMs by tomorrow).

**Comment by bogdandrutu** [comment]
Using admin rights to merge this, non-technical change.

**Pull request merged**
