### PR TITLE
Update 0173-messaging-semantic-conventions.md to include Oracle AQ/TEQ

### PR DESCRIPTION
**Pull request by paulparkinson**
Oracle is very interested in being involved in this endeavor. Thanks.

### CODE REVIEW

**Comment by iNikem** [comment]
We don't usually change accepted OTEPs. Such changes as this can go directly to Spec repo

**Comment by pyohannes** [comment]
The [instrumentation messaging workgroup](https://github.com/open-telemetry/community#special-interest-groups) is actively working on stabilizing messaging semantic conventions, based on this OTEP. We're meeting Thursdays at 8am PST.

@paulparkinson It would be great if somebody from Oracle could participate, to make sure whatever we come up with works for AQ/TEQ.

**Comment by paulparkinson** [comment]
@pyohannes Excellent, thank you for the invite! I will be there.

**Comment by tedsuo** [comment]
@paulparkinson we are marking OTEPs which are no longer being updated as `stale`. We will close this PR in one week. If you wish to resurrect this PR, that is fine.

**Pull request closed without merging**
