### PR TITLE
Migrate CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by trask**
Related to https://github.com/open-telemetry/community/issues/2206

After merging, we can update the require checks in this repo and then I'll send a follow-up to remove the existing CircleCI checks

### CODE REVIEW

**Comment by trask** [comment]
I'm not sure why the new GitHub actions aren't running in this PR, they are running in the PR I sent within my fork: https://github.com/trask/oteps/pull/1

**Comment by jkwatson** [comment]
> I'm not sure why the new GitHub actions aren't running in this PR, they are running in the PR I sent within my fork: [trask#1](https://github.com/trask/oteps/pull/1)

As far as I know, you can't run _new_ workflows as a part of a PR, but if the workflow exists already, you can run the changes. That doesn't explain why it runs on your fork, though...

**Review by arminru — APPROVED** [review]

**Comment by arminru** [comment]
Temporarily bypassing merge requirements so we can iterate on this CI-only change.

**Comment by arminru** [comment]
@trask here you go: https://github.com/open-telemetry/oteps/actions/runs/9894305916

**Pull request merged**
